//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace techstore.techstoreBUS {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="techstoreBUS.techstoreBUSSoap")]
    public interface techstoreBUSSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OnLoad", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet OnLoad();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OnLoad", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> OnLoadAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OnUpdate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int OnUpdate(techstore.techstoreBUS.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OnUpdate", ReplyAction="*")]
        System.Threading.Tasks.Task<int> OnUpdateAsync(techstore.techstoreBUS.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OnInsert", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int OnInsert(techstore.techstoreBUS.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OnInsert", ReplyAction="*")]
        System.Threading.Tasks.Task<int> OnInsertAsync(techstore.techstoreBUS.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OnDelete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int OnDelete(techstore.techstoreBUS.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OnDelete", ReplyAction="*")]
        System.Threading.Tasks.Task<int> OnDeleteAsync(techstore.techstoreBUS.Product product);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Product : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string brandField;
        
        private int priceField;
        
        private string desField;
        
        private bool availableField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string brand {
            get {
                return this.brandField;
            }
            set {
                this.brandField = value;
                this.RaisePropertyChanged("brand");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string des {
            get {
                return this.desField;
            }
            set {
                this.desField = value;
                this.RaisePropertyChanged("des");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool available {
            get {
                return this.availableField;
            }
            set {
                this.availableField = value;
                this.RaisePropertyChanged("available");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface techstoreBUSSoapChannel : techstore.techstoreBUS.techstoreBUSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class techstoreBUSSoapClient : System.ServiceModel.ClientBase<techstore.techstoreBUS.techstoreBUSSoap>, techstore.techstoreBUS.techstoreBUSSoap {
        
        public techstoreBUSSoapClient() {
        }
        
        public techstoreBUSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public techstoreBUSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public techstoreBUSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public techstoreBUSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet OnLoad() {
            return base.Channel.OnLoad();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> OnLoadAsync() {
            return base.Channel.OnLoadAsync();
        }
        
        public int OnUpdate(techstore.techstoreBUS.Product product) {
            return base.Channel.OnUpdate(product);
        }
        
        public System.Threading.Tasks.Task<int> OnUpdateAsync(techstore.techstoreBUS.Product product) {
            return base.Channel.OnUpdateAsync(product);
        }
        
        public int OnInsert(techstore.techstoreBUS.Product product) {
            return base.Channel.OnInsert(product);
        }
        
        public System.Threading.Tasks.Task<int> OnInsertAsync(techstore.techstoreBUS.Product product) {
            return base.Channel.OnInsertAsync(product);
        }
        
        public int OnDelete(techstore.techstoreBUS.Product product) {
            return base.Channel.OnDelete(product);
        }
        
        public System.Threading.Tasks.Task<int> OnDeleteAsync(techstore.techstoreBUS.Product product) {
            return base.Channel.OnDeleteAsync(product);
        }
    }
}
